### PR TITLE
Fix payout

### LINKED ISSUE #146: Payout failing when multiple nodes connected

### PR DESCRIPTION
**Pull request by MakMuftic**
**Multiple minor fixes to payout script**

### PR Checklist

- [x] I have run linter localy
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master
- [x] Updated CHANGELOG.md

### Changes

- fix wrong parameter passed on starting LB server
- fix encoding signature on stats endpoint
- refactor Payout ID to `int` so autoincrement can be used
- extract nonce calculation to separate function, and increment nonce when sending multiple transactions at the same time
- fix downtime query typo

### Issues

Closes #146

### TODO
The number of pings is not calculated properly if LB is restarted #147

### CODE REVIEW

**Review by mpetrun5 — DISMISSED** [review]
@MakMuftic LGTM
What key should you now send to load balancer and how to export it?

**Comment by MakMuftic** [comment]
> @MakMuftic LGTM
> What key should you now send to load balancer and how to export it?

I updated the description of `--private-key` flag inside README file to:

`loadbalancers wallet private key (string representation of hex value prefixed with 0x), used for sending rewards on payout`

@mpetrun5 do you think this is clear enough?

---

For testing purposes, I used the _subkey_ tool. I am not sure how to get this information from _polkadot apps_ but we already are planning to support importing private key from keystore file #140 (that is the file that you can export from _polkadot apps_ as we tried yesterday)

**Comment by mpetrun5** [comment]
> > @MakMuftic LGTM
> > What key should you now send to load balancer and how to export it?
> 
> I updated the description of `--private-key` flag inside README file to:
> 
> `loadbalancers wallet private key (string representation of hex value prefixed with 0x), used for sending rewards on payout`
> 
> @mpetrun5 do you think this is clear enough?
> 
> For testing purposes, I used the _subkey_ tool. I am not sure how to get this information from _polkadot apps_ but we already are planning to support importing private key from keystore file #140 (that is the file that you can export from _polkadot apps_ as we tried yesterday)

Maybe describe the process for using subkey inspection for now for testing purposes.

**Comment by MakMuftic** [comment]
> > > @MakMuftic LGTM
> > > What key should you now send to load balancer and how to export it?
> > 
> > 
> > I updated the description of `--private-key` flag inside README file to:
> > `loadbalancers wallet private key (string representation of hex value prefixed with 0x), used for sending rewards on payout`
> > @mpetrun5 do you think this is clear enough?
> > For testing purposes, I used the _subkey_ tool. I am not sure how to get this information from _polkadot apps_ but we already are planning to support importing private key from keystore file #140 (that is the file that you can export from _polkadot apps_ as we tried yesterday)
> 
> Maybe describe the process for using subkey inspection for now for testing purposes.

@mpetrun5 I added a small paragraph with instructions inside README file

**Review by mpetrun5 — APPROVED** [review]

**Pull request merged**
